# Repository settings are inherited from the base configuration taken from .github repository
# You can redefine needed settings after `_extends` directive
# Settings version: 1.0.0
_extends: .github

